### ISSUE TITLE
error trying to build qri

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri_install#1]
qri_build qri --qri $GOPATH/src/github.com/qri-io/qri
INFO[0000] $ go build -o qri_darwin_amd64/qri /Users/ramfox/go/src/github.com/qri-io/qri
build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined
ERRO[0000] building qri: exit status 1
ERRO[0000] exit status 1

**Comment by dustmop** [comment]
I tried this just now but got a different error:

```
> qri_build qri --qri $GOPATH/src/github.com/qri-io/qri
INFO[0000] $ go build -o qri_darwin_amd64/qri /Users/me/qri/src/github.com/qri-io/qri 
INFO[0232] compressing qri_darwin_amd64.zip. binPath: qri_darwin_amd64/qri templatesPath: templates 
INFO[0243] parsing templates: template: pattern matches no files: `templates/**` 
ERRO[0243] writing qri zip: template: pattern matches no files: `templates/**` 
ERRO[0243] template: pattern matches no files: `templates/**`
```
